const productsTosell = [
  {
    id: 1,
    productName: "PC ONE",
    price: 1500,
    quantity: 1,
    imgProduct: "./img/img_PC.png",
    description: "This is the new arrival, it's made for you",
  },
  {
    id: 2,
    productName: "PC TWO",
    price: 1200,
    quantity: 1,
    imgProduct: "./img/img_PC2.png",
    description: "This is the new arrival, it's made for you",
  },
  {
    id: 3,
    productName: "PC THREE",
    price: 1800,
    quantity: 1,
    imgProduct: "./img/img_PC3.png",
    description: "This is the new arrival, it's made for you",
  },
  {
    id: 4,
    productName: "PC FOUR",
    price: 1900,
    quantity: 1,
    imgProduct: "./img/img_PC4.png",
    description: "This is the new arrival, it's made for you",
  },
  {
    id: 5,
    productName: "LAPTOP ONE",
    price: 2500,
    quantity: 1,
    imgProduct: "./img/img_laptop.png",
    description: "This is the new arrival, it's made for you",
  },
  {
    id: 6,
    productName: "LAPTOP TWO",
    price: 2800,
    quantity: 1,
    imgProduct: "./img/img_laptop2.png",
    description: "This is the new arrival, it's made for you",
  },
  {
    id: 7,
    productName: "LAPTOP THREE",
    price: 3400,
    quantity: 1,
    imgProduct: "./img/img_laptop3.png",
    description: "This is the new arrival, it's made for you",
  },
  {
    id: 8,
    productName: "LAPTOP FOUR",
    price: 5500,
    quantity: 1,
    imgProduct: "./img/img_laptop4.png",
    description: "This is the new arrival, it's made for you",
  },
];
